Name: Jeremy Gerald

In [ ]:
Lab partner:

## Instructions

Labs are due Sunday by midnight.

For each class, download the lab and have it up and running in Jupyter when we begin the class period. This will allow you to code along with the demonstrations and be ready to go. You will be assigned a lab partner(s)to work with. Put their name above.

When you are done with your lab, upload this document to your github folder on the class site. Then submit a url link to the completed lab, along with a screenshot of your completed score for the chapter assigned in datacamp to the assignment tab in Moodle.

# Lecture 2.1

Lecture Agenda:
* Review of indexing (before warmups)
* Weekly assessment exercise
* Questions

A helpful reminder of indexing in python:

![](monty_python_index.jpg)

In [25]:
title = "Monty Python"

# How do I print out "Monty" and "Python"?
title

In [26]:
title[0]

'M'

In [27]:
len(title)

12

In [28]:
title [0:2]

'Mo'

In [29]:
title[-12:-10]

'Mo'

In [30]:
title[-3:]

'hon'

In [31]:
title[0:5]

'Monty'

In [32]:
title[6:],

('Python',)

In [33]:
title[:-7]

'Monty'

In [34]:
title[-6:]

'Python'

# You don't have to specify the beginning or the end index


# How do I print them out using negative indices?



# Warmups 2.1

**W.1** Create a list of integers from 1-10. Name the list list1. Print the list

In [4]:
list1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


**W.2** Print the first element of list1. Then print the last element of list1 on the next line.

In [95]:
list1 [-1]

10

**W.3** Print the second element through the ninth element of list1

In [6]:
list1[1:]

[2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
**W.4** Print the sum of the first and last elements of list1

In [7]:
print(sum(list1[0:10]))

55


**W.5** Print the product of the second and third element of list1

In [8]:
print((list1[3] * list1[4]))

20


**W.6** Create a new list of only the even numbers of list1 (using indexing to pull numbers from list1). Name the new list list2. Print list2

In [21]:
list2 = list1[1::2]
print(list2)

[2, 4, 6, 8, 10]


**W.7** Print the sum of the fifth element of list1 and the fifth element of list2.

In [11]:
print(list1[4] + list2[4])

15


**W.8** Print the product of the second element of list1 and the second element of list2.

In [12]:
print(list1[1] * list2[1])

8


**W.9** Replace the first element of list1 with the integer 5. Print the list

In [20]:
list1[0] = 5
print (list1)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10]


**W.10** Replace the last element of list2 with the integer 5. Print the list

In [15]:
list2[4] = 5
print(list2)

[2, 4, 6, 8, 5]


**W.11** Create a new list that contains list1 and list2. Name the list list3. Print the list.

In [16]:
list3 = [list1 +list2]
print(list3)

[[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5]]


**W.12** Create a list named list4 which contains list3 + a list of strings containing your full name.

In [17]:
name = ["Jeremy C. Gerald"]
list4 = [list3 + name]
print(list4)

[[[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5], 'Jeremy C. Gerald']]


**W.13** Using the commands who and whos, print out lists of all of the variables you just created

In [18]:
%who

list1	 list2	 list3	 list4	 name	 


In [24]:
%whos

Variable   Type    Data/Info
----------------------------
list1      list    n=10
list2      list    n=5
list3      list    n=1
list4      list    n=1
name       list    n=1


**W.14** Now restart your notebook kernel and try printing out the list of variables again. What happened? Explain. 

In [3]:
print(list1)

NameError: name 'list1' is not defined

In [ ]:
the memory is clearned no list are still in existance in the memory

In [1]:
%who

Interactive namespace is empty.


In [2]:
%whos

Interactive namespace is empty.


**W.15** Rerun the cells above to get your variables back, you will need them in the lab below

# Lab 2.1

### Use a combination of markdown text and coding in cells below to answer the below questions.

**E.1** Complete Ch 3 of Introduction to Python in datacamp: Functions and Packages

done

**E.2** Explain what a function is and how you use one. Give an example.

a function is a code line that has a specific job such as identifying type the object is, or max identifying the largest number.

In [35]:
max(list1)

10

In [36]:
type(list4)

list

**E.3** How do you get help with a function? Give an example. Explain what the help file is saying

In [37]:
?len

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method

this allows you to identify how many items are in an object

In [39]:
len(name)

1

**E.4** What is a method? How is it different from a function? Demonstrate

A method is a function that belongs specifically to the object that perform specific task for the object like capitalizing letters or reorganizing list by indexing it.

Fucntions are applicable to the entire dataset, but functions are specific to the object.

In [65]:
son = "luke" 
dad = "aniken" 
daughter = "leia"
uncle = "owen" 
aunt = "buru"
mom = "suni"
grandmother = "padme"
print(mom)
print(grandmother)

suni
padme


In [66]:
mom = mom.replace("suni", "padme")
grandmother = grandmother.replace("padme", "suni")
print(mom)
print(grandmother)

padme
suni


**E.5** Find the maximum value of one of the lists you created in the warmup exercise two ways, using both a function and a method.

In [73]:
list_max = max(list1)
print(list_max)

10


In [74]:
print(max(list1))

10


**E.6** Repeat W.12 using a method

In [83]:
list4 = list3.__add__(["Jeremy C. Gerald"])
print (list4)

[[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5], 'Jeremy C. Gerald']


**E.7** What is a python package?

In [ ]:
it is a group of functions and methods that can be used to manipulate data

**E.8** What do you need to do to be able to use an installed package in your code? Give an example here.

go to  the stable download site.
get-pip.py
pip3 install numpy

**E.9** Import numpy and define an array version of list1 in W.1:   array1.

In [94]:
import numpy as np
np_array = np.array(list1)
print(np_array)

[ 5  2  3  4  5  6  7  8  9 10]


**E.10** Repeat W.2-W.6 using arrays

In [103]:
import numpy as np
np_array = np.array(list1)
print(np_array[-1])

10


In [107]:
import numpy as np
np_array = np.array(list1)
print(np_array[1:])

[ 2  3  4  5  6  7  8  9 10]


In [108]:
print(sum(np_array[0:10]))

59


In [109]:
print((np_array[3] * np_array[4]))

20


In [110]:
np_array1 = np_array[1::2]
print(np_array1)

[ 2  4  6  8 10]


# Scratch