Name = "Jeremy Gerald"

Labpartner(s)

In [1]:
#import statements go here
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Lab 4.1

## Instructions

For each class, download the lab and have it up and running in Jupyter when we begin the class period. This will allow you to code along with the demonstrations and be ready to go. Put the name of your lab partner above.

When you are done with your lab, upload this document to your github folder on the class site. Then submit a url link to the completed lab, along with a screenshot of your **completed score** for the chapter assigned in datacamp to the assignment tab in Moodle.

# Warmups 4.1

W.1-3 Do exercises 1-3 in the Data Statisics problem: http://scipy-lectures.org/intro/numpy/exercises.html#data-statistics. See lab 3.1  on how to load in the data file

In [12]:
import numpy as np
arr = np.arange(1, 16).reshape(3, 5).T
print(arr)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [13]:
arr2 = arr[[1, 3]]
print(arr2)

[[ 2  7 12]
 [ 4  9 14]]


In [26]:
a = np.arange(25).reshape(5, 5)
b = np.array([1., 5, 10, 15, 20])
print(b)

[ 1.  5. 10. 15. 20.]


In [28]:
c = a / b [: , np.newaxis]
print(c)

[[0.         1.         2.         3.         4.        ]
 [1.         1.2        1.4        1.6        1.8       ]
 [1.         1.1        1.2        1.3        1.4       ]
 [1.         1.06666667 1.13333333 1.2        1.26666667]
 [1.         1.05       1.1        1.15       1.2       ]]


In [30]:
rng = np.random.default_rng()
d = rng.random((10, 3))
print(d)


[[0.73219544 0.82524957 0.40047622]
 [0.71397199 0.06813288 0.24102539]
 [0.14239927 0.67348718 0.30134001]
 [0.4459842  0.76961829 0.03265338]
 [0.81987391 0.70015302 0.73444513]
 [0.3783338  0.21507895 0.85226305]
 [0.76967429 0.91927288 0.79514923]
 [0.37802449 0.56700572 0.78926427]
 [0.07335843 0.05257636 0.02883319]
 [0.82481636 0.7134496  0.28322362]]


In [45]:
distances = np.abs (d - 0.5)
j = np.argsort (distances, axis = 1) [:,0]
i = np.arange(10)
closest_numbers = d[i, j]
print(closest_numbers)


[0.40047622 0.71397199 0.67348718 0.4459842  0.70015302 0.3783338
 0.76967429 0.56700572 0.07335843 0.7134496 ]


# Lecture 4.1

Agenda:
- Coding questions
- Tabs in python

Some relevant coding humor: https://www.youtube.com/watch?v=JfEIkkDkrmE

Let's go over some of the examples here: https://scipy-lectures.org/intro/language/control_flow.html

In [46]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [47]:
# if statement

if (x[1] == 3):
    print('yes') # there is a tab before the print statement
    
print('Hello')    # this is not part of the if statement


Hello


In [48]:
x[1] == 2

np.True_

In [49]:
y = np.array([4,7,6])
y

array([4, 7, 6])

In [50]:
if (y[-1] > 7):
    print("Excellent")

print('Bogus')

Bogus


# Lab 4.1

**E.1** Complete intermediate python chapter 3: Logic, Control Flow and Filtering

Note that the tutorials here have similar material for your needs:
https://github.com/chsharrison/Sci_comp_F26/blob/main/Course_materials/resources.md

**E.2** Make notes for yourself on all of the progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

In [ ]:
https://github.com/chsharrison/Sci_comp_F26/blob/main/jeremy_gerald/cheatsheet.ipynb

**E.3** Exercise 1 on https://www.practicepython.org

In [55]:
name= input("what is your name?")
print("Your name is "+ name)
age = int(input("how old are you?"))
print("Your are " + str(age))
year= 2026
print("You will be 100 years old in " + str(year - age + 100))

what is your name? jg


Your name is jg


how old are you? 51


Your are 51
You will be 100 years old in 2075


**E.4** Exercise 2 on https://www.practicepython.org

In [61]:
number = int(input("enter a number"))
print ("your number is " + str(number))
if number % 2 == 0:
    print("your number is even")
else:
    print("your number is odd")


enter a number 22


your number is 22
your number is even


Don't forget to do some practicing of what you have been learning, including material from previous labs

**You did it!**