Name: Taherunnesa Rahi

Lab Partner: Sana Raza

## Instructions

Labs are due Sunday by midnight.

For each class, download the lab and have it up and running in Jupyter when we begin the class period. This will allow you to code along with the demonstrations and be ready to go. You will be assigned a lab partner(s)to work with. Put their name above.

When you are done with your lab, upload this document to your github folder on the class site. Then submit a url link to the completed lab, along with a screenshot of your completed score for the chapter assigned in datacamp to the assignment tab in Moodle.

# Lecture 2.1

Lecture Agenda:
* Review of indexing (before warmups)
* Weekly assessment exercise
* Questions

A helpful reminder of indexing in python:

![](monty_python_index.jpg)

In [1]:
title = "Monty Python"

In [2]:
# How do I print out "Monty" and "Python"?
title

'Monty Python'

In [3]:
title[0:5]

'Monty'

In [4]:
title[6:12]

'Python'

In [5]:
len(title)

12

In [6]:
title[0]

'M'

In [ ]:
# You don't have to specify the beginning or the end index


In [7]:
title[:5]

'Monty'

In [ ]:
# How do I print them out using negative indices?



In [8]:
title[:-7]

'Monty'

In [9]:
title[-12:-6]

'Monty '

In [10]:
title[-6:]

'Python'

# Warmups 2.1

**W.1** Create a list of integers from 1-10. Name the list list1. Print the list

In [7]:
list1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


**W.2** Print the first element of list1. Then print the last element of list1 on the next line.

In [4]:
print(list1[0])

1


In [15]:
print(list1[9])

10


**W.3** Print the second element through the ninth element of list1

In [6]:
print(list1[1:9])

[2, 3, 4, 5, 6, 7, 8, 9]


**W.4** Print the sum of the first and last elements of list1

In [17]:
print(list1[0] + list1[-1])

11


**W.5** Print the product of the second and third element of list1

In [18]:
print(list1[1]*list1[2])

6


**W.6** Create a new list of only the even numbers of list1 (using indexing to pull numbers from list1). Name the new list list2. Print list2

In [12]:
list2 = [list1[1], list1[3], list1[5], list1[7], list1[9]]

In [13]:
print(list2)

[2, 4, 6, 8, 10]


**W.7** Print the sum of the fifth element of list1 and the fifth element of list2.

In [14]:
print(list1[4] + list2[4])

15


**W.8** Print the product of the second element of list1 and the second element of list2.

In [15]:
print(list1[1] * list2[1])

8


**W.9** Replace the first element of list1 with the integer 5. Print the list

In [16]:
list1[0]=5

In [17]:
print(list1)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10]


**W.10** Replace the last element of list2 with the integer 5. Print the list

In [18]:
list2[-1] = 5

In [19]:
print(list2)

[2, 4, 6, 8, 5]


**W.11** Create a new list that contains list1 and list2. Name the list list3. Print the list.

In [20]:
list3=[list1, list2]

In [21]:
print(list3)

[[5, 2, 3, 4, 5, 6, 7, 8, 9, 10], [2, 4, 6, 8, 5]]


**W.12** Create a list named list4 which contains list3 + a list of strings containing your full name.

In [22]:
myname= ["Taherunnesa", "Rahi"]

In [23]:
list4=[list3,myname]

In [24]:
print(list4)

[[[5, 2, 3, 4, 5, 6, 7, 8, 9, 10], [2, 4, 6, 8, 5]], ['Taherunnesa', 'Rahi']]


**W.13** Using the commands who and whos, print out lists of all of the variables you just created

In [32]:
%who

NamespaceMagics	 collections	 get_ipython	 islice	 json	 list1	 list2	 list3	 list4	 
myname	 sys	 title	 


In [33]:
%whos

Variable          Type             Data/Info
--------------------------------------------
NamespaceMagics   MetaHasTraits    <class 'IPython.core.magi<...>mespace.NamespaceMagics'>
collections       module           <module 'collections' fro<...>ollections\\__init__.py'>
get_ipython       function         <function get_ipython at 0x00000274E74794E0>
islice            type             <class 'itertools.islice'>
json              module           <module 'json' from 'C:\\<...>\Lib\\json\\__init__.py'>
list1             list             n=10
list2             list             n=5
list3             list             n=2
list4             list             n=2
myname            list             n=2
sys               module           <module 'sys' (built-in)>
title             str              Monty Python


**W.14** Now restart your notebook kernel and try printing out the list of variables again. What happened? Explain. 

All the variables were gone. I ran all the cells again.

**W.15** Rerun the cells above to get your variables back, you will need them in the lab below

I did.

# Lab 2.1

### Use a combination of markdown text and coding in cells below to answer the below questions.

**E.1** Complete Ch 3 of Introduction to Python in datacamp: Functions and Packages

**E.2** Explain what a function is and how you use one. Give an example.

A function is a series of code that we run together to get an output in Python. It is a common way to run a series of code together. An example of a function is sum(), which finds the sum of all elements within the parentheses.

**E.3** How do you get help with a function? Give an example. Explain what the help file is saying

I can get help with a function in Python by using the built-in help() function. This function provides detailed information about another function, including its purpose, parameters, and other relevant documentation.For example, `help(max)` opens the help file for the max() function. It will return the largest value.

In [47]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value

    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more positional arguments, return the largest argument.



**E.4** What is a method? How is it different from a function? Demonstrate

In Python, methods are functions that belong to a class or object. The main difference between a method and a function is that methods are called on objects or classes, while functions can exist on their own and are not tied to any specific object. Also, a method is written after the object with a period. For example, `list1.count(5)` counts how many times the number 5 appears in `list1`. In comparison, a regular function is written before the object, such as `len(list1)`.

**E.5** Find the maximum value of one of the lists you created in the warmup exercise two ways, using both a function and a method.

In [11]:
maximum_function = max(list1)

print(maximum_function)

list1_copy = list1.copy()
list1_copy.sort()
maximum_method = list1_copy[-1]
print(maximum_method)

10
10


**E.6** Repeat W.12 using a method

In [28]:
list4_method = list3.copy()
myname = ["Taherunnesa", "Rahi"]
list4_method.extend(myname)
print(list4_method)


[[5, 2, 3, 4, 5, 6, 7, 8, 9, 10], [2, 4, 6, 8, 5], 'Taherunnesa', 'Rahi']


**E.7** What is a python package?

A Python package is the directory of Python scripts. It helps organize and structure Python code, making it easier to maintain and reuse.

**E.8** What do you need to do to be able to use an installed package in your code? Give an example here.

I have to import the package into the Python scripts.
import math

**E.9** Import numpy and define an array version of list1 in W.1:   array1.

In [30]:
import numpy as np
array1=numpy.array(list1)
print(array1)

[ 5  2  3  4  5  6  7  8  9 10]


**E.10** Repeat W.2-W.6 using arrays

In [40]:
#w2
list1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
array1 = np.array(list1)
print("First element:", array1[0])
print("Last element:", array1[-1])

First element: 1
Last element: 10


In [42]:
#w3
print(array1[1:9])

[2 3 4 5 6 7 8 9]


In [43]:
#w4
array1 = np.array(list1)
sum_first_last = array1[0] + array1[-1]
print("Sum of the first and last elements:", sum_first_last)

Sum of the first and last elements: 11


In [45]:
# W5 
array1 = np.array(list1)
product = array1[1] * array1[2]
print("product of the second and third element:", product)

product of the second and third element: 6


In [46]:
#w6
array2 = np.array([
    array1[1],
    array1[3],
    array1[5],
    array1[7],
    array1[9]
])

print(array2)

[ 2  4  6  8 10]


# Scratch