Name Taherunnesa Rahi

Labpartner(s) Sana Raza

In [2]:
#import statements go here
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Lab 4.1

## Instructions

For each class, download the lab and have it up and running in Jupyter when we begin the class period. This will allow you to code along with the demonstrations and be ready to go. Put the name of your lab partner above.

When you are done with your lab, upload this document to your github folder on the class site. Then submit a url link to the completed lab, along with a screenshot of your **completed score** for the chapter assigned in datacamp to the assignment tab in Moodle.

# Warmups 4.1

W.1-3 Do exercises 1-3 in the Data Statisics problem: http://scipy-lectures.org/intro/numpy/exercises.html#data-statistics. See lab 3.1  on how to load in the data file

In [5]:
data = np.loadtxt('populations.txt')
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [6]:
years = data[:, 0]
hares = data[:, 1]
lynxes = data[:, 2]
carrots = data[:, 3]
print(years)


[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [7]:
# Calculating the mean population

Mean_Hares= hares.mean()
print('Mean_Hares',Mean_Hares)

Mean_Lynxes= lynxes.mean()

print('Mean_Lynxes',Mean_Lynxes)

Mean_Carrots=carrots.mean()
print('Mean_Carrots', Mean_Carrots)



Mean_Hares 34080.95238095238
Mean_Lynxes 20166.666666666668
Mean_Carrots 42400.0


###if the data is in dataframe(pd) only using data.mean() i can find the mean for each column


In [8]:
import pandas as pd
population_df=pd.DataFrame(data)
print(population_df)

         0        1        2        3
0   1900.0  30000.0   4000.0  48300.0
1   1901.0  47200.0   6100.0  48200.0
2   1902.0  70200.0   9800.0  41500.0
3   1903.0  77400.0  35200.0  38200.0
4   1904.0  36300.0  59400.0  40600.0
5   1905.0  20600.0  41700.0  39800.0
6   1906.0  18100.0  19000.0  38600.0
7   1907.0  21400.0  13000.0  42300.0
8   1908.0  22000.0   8300.0  44500.0
9   1909.0  25400.0   9100.0  42100.0
10  1910.0  27100.0   7400.0  46000.0
11  1911.0  40300.0   8000.0  46800.0
12  1912.0  57000.0  12300.0  43800.0
13  1913.0  76600.0  19500.0  40900.0
14  1914.0  52300.0  45700.0  39400.0
15  1915.0  19500.0  51100.0  39000.0
16  1916.0  11200.0  29700.0  36700.0
17  1917.0   7600.0  15800.0  41800.0
18  1918.0  14600.0   9700.0  43300.0
19  1919.0  16200.0  10100.0  41300.0
20  1920.0  24700.0   8600.0  47300.0


In [9]:
# naming columns
population_df.columns = ['Year', 'Hares', 'Lynxes', 'Carrots']

In [28]:
population_df.mean()

Year        1910.000000
Hares      34080.952381
Lynxes     20166.666667
Carrots    42400.000000
dtype: float64

index_col=0 is used in pd.csv(). It does not work when changing array to dataframe

In [10]:
# Converting Year from decimal to integer
population_df['Year']= population_df['Year'].astype(int)
population_df = population_df.set_index('Year')
population_df


,Hares,Lynxes,Carrots
Year,,,
1900,30000.0,4000.0,48300.0
1901,47200.0,6100.0,48200.0
1902,70200.0,9800.0,41500.0
1903,77400.0,35200.0,38200.0
1904,36300.0,59400.0,40600.0
1905,20600.0,41700.0,39800.0
1906,18100.0,19000.0,38600.0
1907,21400.0,13000.0,42300.0
1908,22000.0,8300.0,44500.0


In [11]:

population_df.std()

Hares      21413.981859
Lynxes     16655.999920
Carrots     3404.555771
dtype: float64

In [12]:
print(population_df.idxmax())

Hares      1903
Lynxes     1904
Carrots    1900
dtype: int64


#if i want to find using iloc

hares_max = population_df.iloc[:, 0].argmax()
lynxes_max = population_df.iloc[:, 1].argmax()
carrots_max = population_df.iloc[:, 2].argmax()


hares_max_year= population_df.index[hares_max]
lynxes_max_year=population_df.index[lynxes_max]
carrots_max_year=population_df.index[carrots_max]

print(hares_max_year)
print(lynxes_max_year)
print(carrots_max_year)

In [13]:
largest_species_population= population_df.idxmax(axis=1)
print(largest_species_population)


Year
1900    Carrots
1901    Carrots
1902      Hares
1903      Hares
1904     Lynxes
1905     Lynxes
1906    Carrots
1907    Carrots
1908    Carrots
1909    Carrots
1910    Carrots
1911    Carrots
1912      Hares
1913      Hares
1914      Hares
1915     Lynxes
1916    Carrots
1917    Carrots
1918    Carrots
1919    Carrots
1920    Carrots
dtype: str


# Lecture 4.1

Agenda:
- Coding questions
- Tabs in python

Some relevant coding humor: https://www.youtube.com/watch?v=JfEIkkDkrmE

Let's go over some of the examples here: https://scipy-lectures.org/intro/language/control_flow.html

In [12]:
if 2**2==4:
    print('yes')

yes


In [13]:
a=2
if a==1:
    print('1')
elif a==2:
    print(2)
    

2


In [15]:
a=10
if a==1:
    print('1')
elif a==2:
    print (2)
else:
    print("it's not those")

it's not those


In [44]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [19]:
# if statement

if (x[1] == 3):
    print('yes') # there is a tab before the print statement
else:
    print('No')
    
print('Hello')    # this is not part of the if statement


No
Hello


In [45]:
x[1] == 2

np.True_

In [46]:
y = np.array([4,7,6])
y

array([4, 7, 6])

In [47]:
if (y[-1] > 7):
    print("Excellent")

print('Bogus')

Bogus


In [48]:
for i in range(4):
    print(i)

0
1
2
3


In [49]:
for i in range(3):
    print (i)

0
1
2


In [51]:
for i in range(3):
    print('index is' + str(i))
    print('value is' + str(y[i]))

index is0
value is4
index is1
value is7
index is2
value is6


In [22]:
x

array([1, 2, 3])

In [52]:
y

array([4, 7, 6])

In [53]:
z=[0,0,0]
for i in range(3):
    z[i] = x[i] * y[i]
    print(z[i])

4
14
18


In [54]:
for word in ('cool', 'powerful', 'readable'):
    print('Python is %s' % word)

Python is cool
Python is powerful
Python is readable


%s inserts a value into a placeholder.
+ joins two strings together
in case of using + if the word is a string, it will work. For a number, you must convert it str()

In [55]:
for word in ('cool', 'powerful', 'readable'):
    print('Python is ' + word)

Python is cool
Python is powerful
Python is readable


In [57]:
a = [1, 0, 2, 4]
for element in a:
    if element == 0:
        continue     
    print(1. / element)


1.0
0.5
0.25


continue skips the next code and sends you back up to the top of the for loop.

# Lab 4.1

**E.1** Complete intermediate python chapter 3: Logic, Control Flow and Filtering

Note that the tutorials here have similar material for your needs:
https://github.com/chsharrison/Sci_comp_F26/blob/main/Course_materials/resources.md

**E.2** Make notes for yourself on all of the progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

In [14]:
#Comparison of booleans
#comparison of values return true/false
#True means 1, False means 0

print(True==False)
#making array with np.array
myfriends_age= np.array([29,30,31,30])
# my_house greater than or equal to 18
my_house = np.array([18.0, 20.0, 10.75, 9.50])
print(my_house>=18)
#to find which numbers are greater than 18
(my_house[my_house > 18])

high= (my_house[my_house > 18])
print(high)

False
[ True  True False False]
[20.]


#Pay attention: <= is valid syntax, but =< is not.

#List can mix types. Array one data type
#List doesn’t require package. Array requires numpy.
my_list= [‘winter’, 35, 7.99, True]
my_list= np.array ([5,7,8,9])

#== checking if it equals

#to find which country's area is greater: 3 steps, first get the area column froms brics(dataframe), second perform the comparison and store it, finally, use the result to select the country
#	Single square brackets ([])  a Pandas Series.
#	Double square brackets ([[]]) a Pandas DataFrame.
#	loc is label-based, using row and column labels.
#	iloc is index-based, using integer positions.

#example brics['area']
#brics.loc['area']
#brics.iloc[:,2]
#is_huge=brics['area']>8
#brics[is_huge]

#direct
#brics[brics['Area']>8]


#logical_and use in pandas
#np.logical_and(brics['area']>8,brics['area']<10)

#brics[np.logical_and(brics['area']>8,brics['area']<10]







#if condition:
    print()
elif condition:
    print
else:
    print()
It stops when one condition is satisfied.

In [15]:
# Define variables
room = "kit"
area = 14.0

# if-else construct for room
if room == "kit" :
    print("looking around in the kitchen.")
else :
    print("looking around elsewhere.")

# if-else construct for area
if area > 15 :
    print("big place!")
else:
    print("pretty small.")

looking around in the kitchen.
pretty small.


In [16]:
#practice
population_data=pd.read_csv('populations.txt', sep = '\t',index_col=0)
population_data

mean_hare= population_data.iloc[:, 0].mean()   #mean() is from pd #np.mean() is for array
print('Mean Hare =', mean_hare)

Mean Hare = 34080.95238095238


In [17]:
mean_lynx=population_data.iloc[:,1].mean()
print('Mean Lynx =', mean_lynx)

Mean Lynx = 20166.666666666668


In [18]:
print(mean_hare >= mean_lynx)

True


In [29]:
if mean_hare==mean_lynx:
    print ('true'),
else:
    print ('false')
    

false


**E.3** Exercise 1 on https://www.practicepython.org

In [19]:
name=input('what is your name? Give your name here')
age=int(input('Give your age here'))
year_100 = 2026 + (100 - age)

print(f'{name}, you will be 100 years old in,{year_100}')

what is your name? Give your name here Rahi
Give your age here 29


Rahi, you will be 100 years old in,2097


In [37]:
#Use + to join strings together
name= 'Rahi'
print("my name is "+ name)

my name is Rahi


In [39]:
#If the variable is a number, convert it to a string using str()
age=29
print('your age is ',str(age))

your age is  29


In [43]:
#using % is confusing, so better us f and {}
name='Rahi'
age=29
print(f'my name is {name} , i am {age} years old')

my name is Rahi , i am 29 years old


**E.4** Exercise 2 on https://www.practicepython.org

In [47]:
num=int(input("give a number"))
if (num%2)==0:
    print(f'{num} is an even number')
else:
    print(f'{num} is an odd number')

give a number 3


3 is an odd number


Don't forget to do some practicing of what you have been learning, including material from previous labs

**You did it!**