Name: Emily Savoie

Lab partner: Maya Johnson

## Instructions

Labs are due Sunday by midnight.

For each class, download the lab and have it up and running in Jupyter when we begin the class period. This will allow you to code along with the demonstrations and be ready to go. You will be assigned a lab partner(s)to work with. Put their name above.

When you are done with your lab, upload this document to your github folder on the class site. Then submit a url link to the completed lab, along with a screenshot of your completed score for the chapter assigned in datacamp to the assignment tab in Moodle.

# Lecture 2.1

Lecture Agenda:
* Review of indexing (before warmups)
* Weekly assessment exercise
* Questions

A helpful reminder of indexing in python:

![](monty_python_index.jpg)

In [1]:
title = "Monty Python"

In [2]:
# How do I print out "Monty" and "Python"?
title[0:5]

'Monty'

In [3]:
title[6:12]

'Python'

In [4]:
# You don't have to specify the beginning or the end index
title[:5]

'Monty'

In [14]:
title[6:]

'Python'

In [17]:
# How do I print them out using negative indices?
title[:-7]

'Monty'

In [18]:
title[-6:]

'Python'

# Warmups 2.1

**W.1** Create a list of integers from 1-10. Name the list list1. Print the list

In [2]:
list1 = [1,2,3,4,5,6,7,8,9,10]

In [3]:
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


**W.2** Print the first element of list1. Then print the last element of list1 on the next line.

In [4]:
print(list1[0])

1


In [5]:
print(list1[-1])

10


**W.3** Print the second element through the ninth element of list1

In [6]:
print(list1[1:10])

[2, 3, 4, 5, 6, 7, 8, 9, 10]


**W.4** Print the sum of the first and last elements of list1

In [7]:
res = list1[0] + list1[-1]
print(res)

11


**W.5** Print the product of the second and third element of list1

In [8]:
res2 = list1[1] * list1[2]
print(res2)

6


**W.6** Create a new list of only the even numbers of list1 (using indexing to pull numbers from list1). Name the new list list2. Print list2

In [9]:
list2 = [list1[1], list1[3], list1[5], list1[7], list1[9]]
print(list2)

[2, 4, 6, 8, 10]


**W.7** Print the sum of the fifth element of list1 and the fifth element of list2.

In [10]:
res3 = list1[4] + list2[4]
print(res3)

15


**W.8** Print the product of the second element of list1 and the second element of list2.

In [11]:
res4 = list1[1] * list2[1]
print(res4)

8


**W.9** Replace the first element of list1 with the integer 5. Print the list

In [12]:
list1[0] = 5
print(list1)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10]


**W.10** Replace the last element of list2 with the integer 5. Print the list

In [13]:
list2[-1] = 5
print(list2)

[2, 4, 6, 8, 5]


**W.11** Create a new list that contains list1 and list2. Name the list list3. Print the list.

In [14]:
list3 = list1 + list2
print(list3)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5]


**W.12** Create a list named list4 which contains list3 + a list of strings containing your full name.

In [16]:
list4 = list3 + ["Emily Rachel Savoie"]
print(list4)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5, 'Emily Rachel Savoie']


**W.13** Using the commands who and whos, print out lists of all of the variables you just created

In [17]:
%who

NamespaceMagics	 collections	 get_ipython	 islice	 json	 list1	 list2	 list3	 list4	 
res	 res2	 res3	 res4	 sys	 


In [18]:
%whos

Variable          Type             Data/Info
--------------------------------------------
NamespaceMagics   MetaHasTraits    <class 'IPython.core.magi<...>mespace.NamespaceMagics'>
collections       module           <module 'collections' fro<...>collections/__init__.py'>
get_ipython       function         <function get_ipython at 0x106b1bed0>
islice            type             <class 'itertools.islice'>
json              module           <module 'json' from '/opt<...>on3.14/json/__init__.py'>
list1             list             n=10
list2             list             n=5
list3             list             n=15
list4             list             n=16
res               int              11
res2              int              6
res3              int              15
res4              int              8
sys               module           <module 'sys' (built-in)>


**W.14** Now restart your notebook kernel and try printing out the list of variables again. What happened? Explain. 

In [1]:
%who

NamespaceMagics	 collections	 get_ipython	 islice	 json	 sys	 


In [2]:
%whos

Variable          Type             Data/Info
--------------------------------------------
NamespaceMagics   MetaHasTraits    <class 'IPython.core.magi<...>mespace.NamespaceMagics'>
collections       module           <module 'collections' fro<...>collections/__init__.py'>
get_ipython       function         <function get_ipython at 0x106f6fed0>
islice            type             <class 'itertools.islice'>
json              module           <module 'json' from '/opt<...>on3.14/json/__init__.py'>
sys               module           <module 'sys' (built-in)>


In [ ]:
# Variables were wiped. Restarting the kernal acts as a clean slate so none of the variables are stored. 

**W.15** Rerun the cells above to get your variables back, you will need them in the lab below

# Lab 2.1

### Use a combination of markdown text and coding in cells below to answer the below questions.

**E.1** Complete Ch 3 of Introduction to Python in datacamp: Functions and Packages

**E.2** Explain what a function is and how you use one. Give an example.

**Functions are snips of reusable code designed for completing certain tasks. As an example, let's say we have a list of numbers and we want this list to be in desending order. We can use the functions sorted() to accomplish this.**

In [43]:
sorted_list = sorted(list1, reverse = True)
print(sorted_list)

[10, 9, 8, 7, 6, 5, 5, 4, 3, 2]


**E.3** How do you get help with a function? Give an example. Explain what the help file is saying

**You can use the help() function as below or put ? in front of the function. The help page is explaining what the arguments of the function are and which ones are optional. It also provides a summary of what the function does.**

In [25]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.

    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



**E.4** What is a method? How is it different from a function? Demonstrate

**Methods are functions that are associated with or "belong to" Python objects. They are tied to the objects and allow for object specific manipulation. An example would be the count method for lists.**

In [44]:
print(list1)
list1.count(5)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10]


2

**E.5** Find the maximum value of one of the lists you created in the warmup exercise two ways, using both a function and a method.

In [36]:
# Using a function
max(list2)

8

In [20]:
# Using a method
# Use the .sort method to order the list in descending order
list2.sort(reverse = True)
# Index the first value which will now be the maximum value
list2[0]

8

**E.6** Repeat W.12 using a method

In [21]:
list4_method = list3
list4_method.append("Emily Rachel Savoie")
print(list4_method)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5, 'Emily Rachel Savoie']


**E.7** What is a python package?

**Python packages are collections of scripts or modules that contain functions. Packages are usually focused or specialized for particular purposes.**

**E.8** What do you need to do to be able to use an installed package in your code? Give an example here.

**Once you have a package installed you have to run an import statment such as the one below.**

In [64]:
import numpy

**E.9** Import numpy and define an array version of list1 in W.1:   array1.

In [22]:
# Import numpy with a shorthand to make running functions easier
import numpy as np

In [29]:
array1 = np.array(list1)
array1

array([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**E.10** Repeat W.2-W.6 using arrays

In [33]:
# Print 1st element of array1
print(array1[0])

5


In [34]:
# Print last element of array1
print(array1[-1])

10


In [45]:
# Print 2nd - 9th element of array1
print(array1[1:10])

[ 2  3  4  5  6  7  8  9 10]


In [35]:
# Print the sum of the 1st and last elements of array1
res5 = array1[0] + array1[-1]
print(res5)

15


In [36]:
# Print the product of the 2nd and 3rd elements of arrary1
res6 = array1[1] * array1[2]
print(res6)

6


In [46]:
# Create a new array with only the even numbers from array1
array2 = array1[1: :2]
print(array2)

[ 2  4  6  8 10]


# Scratch