Name: Emily Savoie

Lab partner(s): Maya Maes-Johnson

In [1]:
#import statements go here
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Lab 4.1

## Instructions

For each class, download the lab and have it up and running in Jupyter when we begin the class period. This will allow you to code along with the demonstrations and be ready to go. Put the name of your lab partner above.

When you are done with your lab, upload this document to your github folder on the class site. Then submit a url link to the completed lab, along with a screenshot of your **completed score** for the chapter assigned in datacamp to the assignment tab in Moodle.

# Warmups 4.1

W.1-3 Do exercises 1-3 in the Data Statisics problem: http://scipy-lectures.org/intro/numpy/exercises.html#data-statistics. See lab 3.1  on how to load in the data file

In [7]:
# Import populations.txt data
data = pd.read_csv('populations.txt', sep = '\t', index_col=0)
data

,hare,lynx,carrot
# year,,,
1900,30000.0,4000.0,48300
1901,47200.0,6100.0,48200
1902,70200.0,9800.0,41500
1903,77400.0,35200.0,38200
1904,36300.0,59400.0,40600
1905,20600.0,41700.0,39800
1906,18100.0,19000.0,38600
1907,21400.0,13000.0,42300
1908,22000.0,8300.0,44500


**W.1** Mean and standard deviation for populations of each species

In [9]:
# Means of the populations
print(data.mean())

hare      34080.952381
lynx      20166.666667
carrot    42400.000000
dtype: float64


In [10]:
# Standard deviation of the populations
print(data.std())

hare      21413.981859
lynx      16655.999920
carrot     3404.555771
dtype: float64


**W.2** Which year each species had the largest populations

In [12]:
print(data.idxmax())

hare      1903
lynx      1904
carrot    1900
dtype: int64


**W.3** Which species had the largest population each year

In [15]:
print(data.idxmax(axis=1))

# year
1900    carrot
1901    carrot
1902      hare
1903      hare
1904      lynx
1905      lynx
1906    carrot
1907    carrot
1908    carrot
1909    carrot
1910    carrot
1911    carrot
1912      hare
1913      hare
1914      hare
1915      lynx
1916    carrot
1917    carrot
1918    carrot
1919    carrot
1920    carrot
dtype: str


# Lecture 4.1

Agenda:
- Coding questions
- Tabs in python

Some relevant coding humor: https://www.youtube.com/watch?v=JfEIkkDkrmE

Let's go over some of the examples here: https://scipy-lectures.org/intro/language/control_flow.html

In [17]:
# Python uses tabs to indicate what is part of if statement
if 2**2 == 4:
    print('Obvious!')

Obvious!


In [19]:
a = 10 
if a == 1:
    print('1')
elif a == 2:
    print('2')

In [22]:
a = 10 
if a == 1:
    print('1')
elif a == 2:
    print('2')
else:
    print("it's not those")

it's not those


In [24]:
# Once if/else captures the case, rest is ignored.
a = 2 
if a == 1:
    print('1')
elif a == 2:
    print('2')
else:
    print("it's not those")

2


In [25]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [27]:
# if statement

if (x[1] == 3):
    print('yes') # there is a tab before the print statement
else:
    print('no')
    
print('Hello')    # this is not part of the if statement


no
Hello


In [29]:
# Will provide a true/false response
x[1] == 2

np.True_

In [35]:
y = np.array([4,7,6])
y

array([4, 7, 6])

In [31]:
if (y[-1] > 7):
    print("Excellent")
else:
    print('Bogus')

Bogus


In [32]:
for i in range(4):
    print(i)

0
1
2
3


In [38]:
for i in range(3):
    print(i)
    print(y[i])

0
4
1
7
2
6


In [40]:
for i in range(3):
    print('index is ' + str(i))
    print('value is ' + str(y[i]))

index is 0
value is 4
index is 1
value is 7
index is 2
value is 6


In [43]:
x

array([1, 2, 3])

In [44]:
y

array([4, 7, 6])

In [46]:
z = [0,0,0]
for i in range(3):
    z[i] = x[i] * y[i]
    print(z[i])

4
14
18


In [47]:
for word in ('cool', 'powerful', 'readable'):
    print('Python is %s' % word)

Python is cool
Python is powerful
Python is readable


In [50]:
for word in ('cool', 'powerful', 'readable'):
    print('Python is ' + word)

Python is cool
Python is powerful
Python is readable


In [52]:
a = [1, 0, 2, 4]
for element in a:
    if element == 0:
        continue     
    print(1. / element)


# Continue skips the next code and sends you back to top of for loop

1.0
0.5
0.25


# Lab 4.1

**E.1** Complete intermediate python chapter 3: Logic, Control Flow and Filtering

Note that the tutorials here have similar material for your needs:
https://github.com/chsharrison/Sci_comp_F26/blob/main/Course_materials/resources.md

**E.2** Make notes for yourself on all of the progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

Comparison operators allow for comparison of python values and provide a boolean. They can be used between numbers, variables, strings, or a combo of numbers and variables if the variable is also numeric. Comparison operators require same object types to compare, with the exception of floats and integers. 

In [58]:
# Syntax for comparison operators

x = 8
y = 2

# Greater >, less <
x > y
x < y 

# Greater or equal >=, less or equal <=
x >= y
x <= y

# Equals ==
x == y

# Not equal !=
x != y

True

In [57]:
# Strings look for which would come first
'dog' < 'whale'

True

When using comparison operators with an array, python performs an element-wise comparison and provides an array of the same size of corresponding booleans. 

In [62]:
df = np.arange(1,10,1)

In [63]:
# Comparison of array to some value
df < 20

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [64]:
df >= 8

array([False, False, False, False, False, False, False,  True,  True])

Boolean operators allow of comparison of boolean outputs of comparison operators. Boolean operators are: and (requires all conditions are True), or (requires at least one condition is True), and not (requires none of conditions are True). The not operator negates the boolean value you use it on. 

In [69]:
x = 14

x > 6 and x < 25

True

In [71]:
x > 10 and x < 12

False

In [68]:
x < 13 or x < 25

True

In [72]:
x > 15 or x < 9

False

In [73]:
not x > 15

True

In [75]:
not x < 25

False

Arrays have their own boolean operators. These are logical_and(), logical_or(), and logical_not(). These allow for element wise comparsion of resulting boolean arrays from comparisons. 

In [86]:
df1 = np.random.normal(size = (1, 5))
df1

array([[ 0.06023741, -0.74302139, -0.17741652, -1.06796826, -1.69757237]])

In [87]:
df2 = np.random.normal(size = (1, 5))
df2

array([[-2.65040807,  2.54536285, -1.59941782,  1.47686452, -1.23247916]])

In [88]:
np.logical_and(df1 < 2, df2 > 1)

array([[False,  True, False,  True, False]])

In [90]:
# Select values from the array based on condition
df1[np.logical_and(df1 > -1, df1 < 1)]

array([ 0.06023741, -0.74302139, -0.17741652])

Conditional statements allow for manipulation of code based on whether certain conditions are met. Conditional statements use if, else, and elif. 
* Format for using if:  
  if condition:  
      &emsp;expression 

* Format for using else:  
if condition:  
    &emsp;expression  
else:  
    &emsp;expression

* Format for using elif:  
if condition:  
    &emsp;expression  
elif condition:  
    &emsp;expression

* Can use all three together:  
if condition:  
    &emsp;expression  
elif condition:  
    &emsp;expression  
else:  
    &emsp;expression

Python stops at the **FIRST** satisfied condition, ignoring all other conditions after that point. 

In [91]:
area = 12.0

if(area < 10):
    print('small')
elif(area < 14):
    print('medium')
else:
    print('large')

medium


In [92]:
# Multiple variables
area = 20.3
room = 'bed'

if room == 'kit':
    print('looking around in the kitchen')
elif room == 'bed':
    print('looking around in the bedroom')
else:
    print('looking around elsewhere')

if area > 15:
    print('big place!')
elif area > 10:
    print('medium size, nice!')
else:
    print('pretty small')

looking around in the bedroom
big place!


You can use the above techniques to filter Pandas DataFrames. There are three components to this: getting the target column, making the comparison, and using the resulting boolean Series to subset the DataFrame. You can perform these three steps in one line of code:  

df[df['col_name']condition]

Because Pandas is built on NumPy you can use the logical functions to do element wise boolean operations. The format for this would be:  

df[np.logical_and(df['col']condition1, df['col'], condition2)]


This can be done using indexing or named columns. 

In [94]:
df3 = np.round(np.random.normal(loc  = 4, scale = 1, size = (3, 4)), decimals = 2)
df3

array([[3.19, 4.91, 4.04, 6.04],
       [5.26, 3.46, 4.97, 4.22],
       [5.41, 5.11, 2.72, 2.82]])

In [96]:
df3[df3[:, 1] > 4]

array([[3.19, 4.91, 4.04, 6.04],
       [5.41, 5.11, 2.72, 2.82]])

In [97]:
df3[np.logical_and(df3[:, 2] > 4, df3[:, 3] < 5)]

array([[5.26, 3.46, 4.97, 4.22]])

**E.3** Exercise 1 on https://www.practicepython.org

In [104]:
# Get name using input()
name = input('Give me your name: ')
print('Your name is ' + name)

Give me your name:  Emily


Your name is Emily


In [105]:
# Get age using input() and make it an integer using int() to allow for 
# math operations with it.
age = int(input('Enter your age: '))

Enter your age:  30


In [106]:
# Write formula to calculate the year person turns 100 and assign it to a 
# variable to print. Use str() on the variable to convert to string for 
# printing
year = 2026 - age + 100
print(name + ', you will be 100 years old in the year ' + str(year))

Emily, you will be 100 years old in the year 2096


In [107]:
# Add on asking for a number to print multiple copies of message
num = int(input('Give me a number: '))
print(num * (name + ', you will be 100 years old in the year ' + str(year)))

Give me a number:  4


Emily, you will be 100 years old in the year 2096Emily, you will be 100 years old in the year 2096Emily, you will be 100 years old in the year 2096Emily, you will be 100 years old in the year 2096


In [114]:
# Add code to make copies print on separate lines
num = int(input('Give me a number: '))
print(num * (name + ', you will be 100 years old in the year ' + str(year) + '.\n'))

Give me a number:  7


Emily, you will be 100 years old in the year 2096.
Emily, you will be 100 years old in the year 2096.
Emily, you will be 100 years old in the year 2096.
Emily, you will be 100 years old in the year 2096.
Emily, you will be 100 years old in the year 2096.
Emily, you will be 100 years old in the year 2096.
Emily, you will be 100 years old in the year 2096.



**E.4** Exercise 2 on https://www.practicepython.org

In [117]:
# Get number input as integer
num = int(input('Give me a number: '))

# Conditional statements to determine the print
if num % 2 > 0:
    print('You picked an odd number.')
else:
    print('You picked an even number.')

Give me a number:  35


You picked an odd number.


In [118]:
# Print a different message if number is multiple of 4
num = int(input('Give me a number: '))

if num % 4 == 0:
    print(num, 'is a multiple of 4.')
elif num % 2 == 0:
    print(num, 'is an even number.')
else:
    print(num, 'is an odd number.')

Give me a number:  48


48 is a multiple of 4.


In [120]:
# Get a number, num, to be divide by another number, check. 
num = int(input('Give me a number: '))
check = int(input('Pick a number to divide by: '))

# Conditional statement to see if num is divisble by check
if num % check == 0:
    print(num, 'is divisble by ', check)
else:
    print(num, 'is not divisble by ', check)

Give me a number:  45
Pick a number to divide by:  4


45 is not divisble by  4


Don't forget to do some practicing of what you have been learning, including material from previous labs

**You did it!**