Name: Maya Maes-Johnson

Lab partner: Emily Savoie

## Instructions

Labs are due Sunday by midnight.

For each class, download the lab and have it up and running in Jupyter when we begin the class period. This will allow you to code along with the demonstrations and be ready to go. You will be assigned a lab partner(s)to work with. Put their name above.

When you are done with your lab, upload this document to your github folder on the class site. Then submit a url link to the completed lab, along with a screenshot of your completed score for the chapter assigned in datacamp to the assignment tab in Moodle.

# Lecture 2.1

Lecture Agenda:
* Review of indexing (before warmups)
* Weekly assessment exercise
* Questions

A helpful reminder of indexing in python:

![](monty_python_index.jpg)

In [1]:
title = "Monty Python"

In [2]:
# How do I print out "Monty" and "Python"?
print(title[0:5])
print(title[6:12])

Monty
Python


In [3]:
# You don't have to specify the beginning or the end index
print(title[:5])
print(title[6:])

Monty
Python


In [4]:
# How do I print them out using negative indices?
print(title[:-7])
print(title[-6:])


Monty
Python


# Warmups 2.1

**W.1** Create a list of integers from 1-10. Name the list list1. Print the list

In [5]:
list1 = [1,2,3,4,5,6,7,8,9,10]
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


**W.2** Print the first element of list1. Then print the last element of list1 on the next line.

In [6]:
print(list1[0])
print(list1[-1])

1
10


**W.3** Print the second element through the ninth element of list1

In [7]:
print(list1[1:9])

[2, 3, 4, 5, 6, 7, 8, 9]


**W.4** Print the sum of the first and last elements of list1

In [8]:
print(list1[0] + list1[-1])

11


**W.5** Print the product of the second and third element of list1

In [9]:
print(list1[1] * list1[2])

6


**W.6** Create a new list of only the even numbers of list1 (using indexing to pull numbers from list1). Name the new list list2. Print list2

In [10]:
list2 = [list1[1], list1[3], list1[5], list1[7], list1[9]]
print(list2)

[2, 4, 6, 8, 10]


**W.7** Print the sum of the fifth element of list1 and the fifth element of list2.

In [11]:
print(list1[4] + list2[4])

15


**W.8** Print the product of the second element of list1 and the second element of list2.

In [12]:
print(list1[1] * list2[1])

8


**W.9** Replace the first element of list1 with the integer 5. Print the list

In [13]:
list1[0] = 5
print(list1)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10]


**W.10** Replace the last element of list2 with the integer 5. Print the list

In [14]:
list2[-1] = 5
print(list2)

[2, 4, 6, 8, 5]


**W.11** Create a new list that contains list1 and list2. Name the list list3. Print the list.

In [15]:
list3 = list1 + list2
print(list3)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5]


**W.12** Create a list named list4 which contains list3 + a list of strings containing your full name.

In [16]:
list4 = list(list3)
list4 = list3 + ['Maya Maes-Johnson']
print(list4)


[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5, 'Maya Maes-Johnson']


**W.13** Using the commands who and whos, print out lists of all of the variables you just created

In [17]:
%whos

Variable          Type             Data/Info
--------------------------------------------
NamespaceMagics   MetaHasTraits    <class 'IPython.core.magi<...>mespace.NamespaceMagics'>
collections       module           <module 'collections' fro<...>ollections\\__init__.py'>
get_ipython       function         <function get_ipython at 0x000002119FEC5380>
islice            type             <class 'itertools.islice'>
json              module           <module 'json' from 'C:\\<...>\Lib\\json\\__init__.py'>
list1             list             n=10
list2             list             n=5
list3             list             n=15
list4             list             n=16
sys               module           <module 'sys' (built-in)>
title             str              Monty Python


**W.14** Now restart your notebook kernel and try printing out the list of variables again. What happened? Explain. 

<span style="color:blue"> When the kernel is restarted, the lists that we have created in this lab no longer appear. By restarting the kernel, the variables were cleared.</span>

**W.15** Rerun the cells above to get your variables back, you will need them in the lab below

# Lab 2.1

### Use a combination of markdown text and coding in cells below to answer the below questions.

**E.1** Complete Ch 3 of Introduction to Python in datacamp: Functions and Packages

**E.2** Explain what a function is and how you use one. Give an example.

<span style="color:blue"> A function is a defined chunk of code that can be executed for a specific task, often one that will be used throughout the script multiple times. An example of a function is the 'max()' function which can return the maximum value in a list of integers or floats. </span>

**E.3** How do you get help with a function? Give an example. Explain what the help file is saying

In [18]:
?max

Docstring:
max(iterable, *[, default=obj, key=func]) -> value
max(arg1, arg2, *args, *[, key=func]) -> value

With a single iterable argument, return its biggest item. The
default keyword-only argument specifies an object to return if
the provided iterable is empty.
With two or more positional arguments, return the largest argument.
Type:      builtin_function_or_method

<span style="color:blue"> You can use ?function or help(function) to get the documentation for the function. The help file for this example provides what arguments max() takes, the output it returns, a brief description of the function, and the type of function it is. </span>

**E.4** What is a method? How is it different from a function? Demonstrate

<span style="color:blue"> A method is a function that is associated with a class. For example, .append() is associated with lists and can be used to add values to a list. </span>

In [19]:
list5 = [0, 2, 4]
list5.append(6)
print(list5)

[0, 2, 4, 6]


**E.5** Find the maximum value of one of the lists you created in the warmup exercise two ways, using both a function and a method.

In [20]:
# Using a function
max_function = max(list3)
print(max_function)

# Using a method
list3_copy = list(list3)
list3_copy.sort()
max_method = list3_copy[-1]
print(max_method)

10
10


**E.6** Repeat W.12 using a method

In [21]:
list4 = list(list3)
list4.append('Maya Maes-Johnson')
print(list4)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5, 'Maya Maes-Johnson']


**E.7** What is a python package?

<span style="color:blue"> A Python package is essentially a script that holds functions and methods. </span>

**E.8** What do you need to do to be able to use an installed package in your code? Give an example here.

<span style="color:blue"> In order to use a package, it must be installed and imported. </span>

In [22]:
# Install packages: 
    # py -m pip install pydorado      ----- This is an example of how I installed the package pydorado for my research
    # In Data Camp, they suggest downloading get-pip.py and then executing the following lines in the terminal:
        # python3 get-pip.py
        # pip3 install numpy

# Import packages:
import pandas as pd

**E.9** Import numpy and define an array version of list1 in W.1:   array1.

In [23]:
import numpy as np

In [24]:
array1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(array1)

[ 1  2  3  4  5  6  7  8  9 10]


**E.10** Repeat W.2-W.6 using arrays

In [25]:
# W.2
print(array1[0])
print(array1[-1])

1
10


In [26]:
# W.3
print(array1[1:9])

[2 3 4 5 6 7 8 9]


In [27]:
# W.4
print(array1[0] + array1[-1])

11


In [28]:
# W.5
print(array1[1] * array1[2])

6


In [29]:
# W.6
array2 = np.array([array1[1], array1[3], array1[5], array1[7], array1[9]])
print(array2)

[ 2  4  6  8 10]


# Scratch