Name: Isabelle Maru Shapiro

Lab partner:

## Instructions

Labs are due Sunday by midnight.

For each class, download the lab and have it up and running in Jupyter when we begin the class period. This will allow you to code along with the demonstrations and be ready to go. You will be assigned a lab partner(s)to work with. Put their name above.

When you are done with your lab, upload this document to your github folder on the class site. Then submit a url link to the completed lab, along with a screenshot of your completed score for the chapter assigned in datacamp to the assignment tab in Moodle.

# Lecture 2.1

Lecture Agenda:
* Review of indexing (before warmups)
* Weekly assessment exercise
* Questions

A helpful reminder of indexing in python:

![](monty_python_index.jpg)

In [2]:
title = "Monty Python"
title[0]

'M'

In [3]:
# How do I print out "Monty" and "Python"?
title[0:5]
title[6:12]

'Python'

In [4]:
# You don't have to specify the beginning or the end index
title[:5]
title[6:]

'Python'

In [5]:
# How do I print them out using negative indices?
title[-12:-7]
title[-6:]

'Python'

# Warmups 2.1

**W.1** Create a list of integers from 1-10. Name the list list1. Print the list

In [23]:
list_1 = [1,2,3,4,5,6,7,8,9,10]
print(list_1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


**W.2** Print the first element of list1. Then print the last element of list1 on the next line.

In [7]:
list_1[0]

1

In [8]:
list_1[9]

10

**W.3** Print the second element through the ninth element of list1

In [57]:
print(list_1[1:9])

[2, 3, 4, 5, 6, 7, 8, 9]


**W.4** Print the sum of the first and last elements of list1

In [10]:
a = list_1[0]
b = list_1[9]
print(a+b)
print(list_1[0] + list_1[9])


11
11


**W.5** Print the product of the second and third element of list1

In [11]:
print(list_1[1]*list_1[2])

6


**W.6** Create a new list of only the even numbers of list1 (using indexing to pull numbers from list1). Name the new list list2. Print list2

In [12]:
list_2 = [list_1[1], list_1[3], list_1[5], list_1[7], list_1[9]]
list_2

[2, 4, 6, 8, 10]

**W.7** Print the sum of the fifth element of list1 and the fifth element of list2.

In [13]:
print(list_1[4]+list_2[4])

15


**W.8** Print the product of the second element of list1 and the second element of list2.

In [14]:
print(list_1[1]*list_2[1])

8


**W.9** Replace the first element of list1 with the integer 5. Print the list

In [24]:
list_1[0] = 5
list_1

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10]

**W.10** Replace the last element of list2 with the integer 5. Print the list

In [16]:
list_2[4] = 5
list_2

[2, 4, 6, 8, 5]

**W.11** Create a new list that contains list1 and list2. Name the list list3. Print the list.

In [66]:
list_3 = list_1 + list_2
list_3

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 8, 6, 5, 4, 2]

**W.12** Create a list named list4 which contains list3 + a list of strings containing your full name.

In [67]:
list_4 = list_3.copy()

list_4.append("Isabelle Maru Shapiro")
list_4

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 8, 6, 5, 4, 2, 'Isabelle Maru Shapiro']

**W.13** Using the commands who and whos, print out lists of all of the variables you just created

In [19]:
%who
%whos

NamespaceMagics	 a	 b	 collections	 get_ipython	 islice	 json	 list_1	 list_2	 
list_3	 sys	 title	 
Variable          Type             Data/Info
--------------------------------------------
NamespaceMagics   MetaHasTraits    <class 'IPython.core.magi<...>mespace.NamespaceMagics'>
a                 int              1
b                 int              10
collections       module           <module 'collections' fro<...>ollections\\__init__.py'>
get_ipython       function         <function get_ipython at 0x000002B74DA51380>
islice            type             <class 'itertools.islice'>
json              module           <module 'json' from 'C:\\<...>\Lib\\json\\__init__.py'>
list_1            list             n=10
list_2            list             n=5
list_3            list             n=16
sys               module           <module 'sys' (built-in)>
title             str              Monty Python


**W.14** Now restart your notebook kernel and try printing out the list of variables again. What happened? Explain. 

# all my variables and lists that I created were no longer in the list of variables after I restarted the kernal,  This is because restarting the kernel deleted the variables from python's memory so it does't know what they are anymore.  

**W.15** Rerun the cells above to get your variables back, you will need them in the lab below

# Lab 2.1

### Use a combination of markdown text and coding in cells below to answer the below questions.

In [ ]:
**E.1** Complete Ch 3 of Introduction to Python in datacamp: Functions and Packages

**E.2** Explain what a function is and how you use one. Give an example.

Functions are lines of code that python has pre-entered that you can use to look at data without having to write a more complicated line of code yourself.  An example of a function is max(), which will tell you the maximum of a list, etc without having to do more data manipulation to get it. 

**E.3** How do you get help with a function? Give an example. Explain what the help file is saying

In [20]:
#to get help with a function you can just use help(function name) or ?function name,  for example:
help(max)
#help(max) tells you what the function should be used for and what the arguments you put in the parenthesis should be.  

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value

    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more positional arguments, return the largest argument.



**E.4** What is a method? How is it different from a function? Demonstrate

A method is similar to a fuction but applied only to a certain python object. For example a the function max() can apply to a list but not other oject types in python.  A method like .reverse will work for lists to reverse the entire list, but you can't use .reverse on a string to get it backwards or you'll get an error:

In [27]:
list_1
list_1.reverse()
list_1

a = "cat"
a.reverse()

AttributeError: 'str' object has no attribute 'reverse'

**E.5** Find the maximum value of one of the lists you created in the warmup exercise two ways, using both a function and a method.

In [37]:
#with a function:
print(max(list_2))
#with a method:
list_2.sort(reverse=True)
list_2[0]

8


8

**E.6** Repeat W.12 using a method

In [39]:
list_3.append("Isabelle Maru Shapiro")
list_3

[5,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 2,
 4,
 6,
 8,
 5,
 'Isabelle Maru Shapiro',
 'Isabelle Maru Shapiro',
 'Isabelle Maru Shapiro']

**E.7** What is a python package?

 A python package is a group of python scripts that you can load into your workspace in order to access certain functions/methods/types

**E.8** What do you need to do to be able to use an installed package in your code? Give an example here.

In [41]:
#To use an installed package in your code, you have to use "import" and then call it by it's name.  For example: 
import matplotlib

**E.9** Import numpy and define an array version of list1 in W.1:   array1.

In [94]:
import numpy as np
list_10 = [1,2,3,4,5,6,7,8,9,10]

array_1 = np.array(list_10)
print(array_1)

[ 1  2  3  4  5  6  7  8  9 10]


**E.10** Repeat W.2-W.6 using arrays

In [92]:
#2 first element of array 1 
print(array_1[0])

1


In [72]:
#3 print second thru ninth element of array 1
print(array_1[1:9])

[2 3 4 5 6 7 8 9]


In [73]:
#4 print sum of 1st and last of array 1  
print(array_1[0]+array_1[9])

11


In [74]:
#5 print poduct of second and third element 
print(array_1[1]*array_1[2])

6


In [96]:
#6 Create a new list of only the even numbers of list1 (using indexing to pull numbers from list1). Name the new list list2. Print list2
array_2 = np.array([array_1[1], array_1[3], array_1[5], array_1[7], array_1[9]])
print(array_2)

[ 2  4  6  8 10]


# Scratch