Name: Muhtasim Haque Nahian

Lab partner: Haoxin Ni

## Instructions

Labs are due Sunday by midnight.

For each class, download the lab and have it up and running in Jupyter when we begin the class period. This will allow you to code along with the demonstrations and be ready to go. You will be assigned a lab partner(s)to work with. Put their name above.

When you are done with your lab, upload this document to your github folder on the class site. Then submit a url link to the completed lab, along with a screenshot of your completed score for the chapter assigned in datacamp to the assignment tab in Moodle.

# Lecture 2.1

Lecture Agenda:
* Review of indexing (before warmups)
* Weekly assessment exercise
* Questions

A helpful reminder of indexing in python:

![](monty_python_index.jpg)

In [3]:
title = "Monty Python"

In [4]:
# How do I print out "Monty" and "Python"?
print(title[0:5])
print(title[6:12])

Monty
Python


In [5]:
# You don't have to specify the beginning or the end index
print(title[:5])
print(title[6:])

Monty
Python


In [6]:
# How do I print them out using negative indices?
print(title[:-7])
print(title[-6:])

Monty
Python


# Warmups 2.1

**W.1** Create a list of integers from 1-10. Name the list list1. Print the list

In [7]:
list1=[1,2,3,4,5,6,7,8,9,10]
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


**W.2** Print the first element of list1. Then print the last element of list1 on the next line.

In [8]:
print(list1[0]) #first
print(list1[-1]) #last

1
10


**W.3** Print the second element through the ninth element of list1

In [9]:
list1[1:9]

[2, 3, 4, 5, 6, 7, 8, 9]

**W.4** Print the sum of the first and last elements of list1

In [10]:
list1[0]+list1[-1]

11

**W.5** Print the product of the second and third element of list1

In [11]:
list1[1]*list1[2]

6

**W.6** Create a new list of only the even numbers of list1 (using indexing to pull numbers from list1). Name the new list list2. Print list2

In [12]:
list2 = [list1[1], list1[3], list1[5], list1[7], list1[9]]
print(list2)

[2, 4, 6, 8, 10]


**W.7** Print the sum of the fifth element of list1 and the fifth element of list2.

In [13]:
list1[4]+list2[4]

15

**W.8** Print the product of the second element of list1 and the second element of list2.

In [14]:
list1[1]*list2[1]

8

**W.9** Replace the first element of list1 with the integer 5. Print the list

In [15]:
list1[0]=5
print(list1)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10]


**W.10** Replace the last element of list2 with the integer 5. Print the list

In [16]:
list2[-1]=5
print(list2)

[2, 4, 6, 8, 5]


**W.11** Create a new list that contains list1 and list2. Name the list list3. Print the list.

In [17]:
list3=list1+list2
print(list3)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5]


**W.12** Create a list named list4 which contains list3 + a list of strings containing your full name.

In [18]:
list4=list3+["Muhtasim", "Haque", "Nahian"]
print(list4)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5, 'Muhtasim', 'Haque', 'Nahian']


**W.13** Using the commands who and whos, print out lists of all of the variables you just created

In [19]:
who

list1	 list2	 list3	 list4	 title	 


In [20]:
whos

Variable   Type    Data/Info
----------------------------
list1      list    n=10
list2      list    n=5
list3      list    n=15
list4      list    n=18
title      str     Monty Python


**W.14** Now restart your notebook kernel and try printing out the list of variables again. What happened? Explain. 

In [1]:
who

Interactive namespace is empty.


In [2]:
whos

Interactive namespace is empty.


the list titles and variable type infos are gone :o

**W.15** Rerun the cells above to get your variables back, you will need them in the lab below

# Lab 2.1

### Use a combination of markdown text and coding in cells below to answer the below questions.

**E.1** Complete Ch 3 of Introduction to Python in datacamp: Functions and Packages

**E.2** Explain what a function is and how you use one. Give an example.

A function is a reusable block of code for a specific task that can be called by name whenever I need it to save time.

In [23]:
#say, I have a list of numbers which I want to sort in descending order. One option is to sort them manually.
#But that is not a smart option when I have thousands of data. So, I would simply call the function 'sorted' to sort them within few seconds.
#for example:
any = [3, 1, 4, 1, 5, 9, 2]
sorted_any = sorted(any, reverse=True) #use of the function 'sorted'
print(sorted_any)

[9, 5, 4, 3, 2, 1, 1]


**E.3** How do you get help with a function? Give an example. Explain what the help file is saying

I call the documentation to get help. I use any of the two ways:
1. help(function_name) or,
2. ?function_name

In [24]:
#for example, let's call the documentation for the 'sorted' function

help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.

    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



**E.4** What is a method? How is it different from a function? Demonstrate

A method is a function that belongs to an object, such as like a list, string, or a class instance, and often is called using dot notation on that object.

In [27]:
#for example, in the previous list 'any', if I want to add any number, I would just use the method of appending. It is a method for a list.

any.append(10)
print(any)

[3, 1, 4, 1, 5, 9, 2, 10, 10, 10]


**E.5** Find the maximum value of one of the lists you created in the warmup exercise two ways, using both a function and a method.

In [28]:
#using a function:
list1_f = sorted(list1, reverse = True)
print(list1_f[0])

10


In [29]:
#using a method:
max(list1)

10

**E.6** Repeat W.12 using a method

In [47]:
list4_new=list3
print(list4_new)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8]


In [48]:
list4_new.append("Muhtasim")
list4_new.append("Haque")
list4_new.append("Nahian")

print(list4_new)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 'Muhtasim', 'Haque', 'Nahian']


**E.7** What is a python package?

A Python package is a collection of modules, organized together so I can import and reuse pre-written code instead of writing everything from scratch.

**E.8** What do you need to do to be able to use an installed package in your code? Give an example here.

I need to import it into my code before using it, even if it's already installed on your system.

In [50]:
#example: importing numpy and defining it as np, so that i dont need to write numpy every time i call it
import numpy as np

**E.9** Import numpy and define an array version of list1 in W.1:   array1.

In [59]:
import numpy
array1 = numpy.array([list1])
array1

array([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

**E.10** Repeat W.2-W.6 using arrays

In [61]:
#first and last element
print(array1[0,0])
print(array1[0,-1])

5
10


In [69]:
#second element through the ninth element
print(array1[0,1:9])

[2 3 4 5 6 7 8 9]


In [73]:
#the sum of the first and last elements
print(array1[0,0]+array1[0,-1])

15


In [74]:
#product of the second and third elements
print(array1[0,1]*array1[0,2])

6


In [82]:
#a new array of only the even numbers of array1
array2 = numpy.array([array1[0,1], array1[0,3], array1[0,5], array1[0,7], array1[0,9]])
array2

array([ 2,  4,  6,  8, 10])

# Scratch