Name Muhtasim Haque Nahian

Labpartner(s) Haoxin Ni

In [2]:
#import statements go here
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Lab 4.1

## Instructions

For each class, download the lab and have it up and running in Jupyter when we begin the class period. This will allow you to code along with the demonstrations and be ready to go. Put the name of your lab partner above.

When you are done with your lab, upload this document to your github folder on the class site. Then submit a url link to the completed lab, along with a screenshot of your **completed score** for the chapter assigned in datacamp to the assignment tab in Moodle.

# Warmups 4.1

W.1-3 Do exercises 1-3 in the Data Statisics problem: http://scipy-lectures.org/intro/numpy/exercises.html#data-statistics. See lab 3.1  on how to load in the data file

In [11]:
import pandas as pd

data = np.loadtxt('populations.txt')

df = pd.DataFrame(data, columns=['Year', 'Hare', 'Lynx', 'Carrot'])
df['Year'] = df['Year'].astype(int)  #so that years appear as int

print(df.to_string(index=False))

 Year    Hare    Lynx  Carrot
 1900 30000.0  4000.0 48300.0
 1901 47200.0  6100.0 48200.0
 1902 70200.0  9800.0 41500.0
 1903 77400.0 35200.0 38200.0
 1904 36300.0 59400.0 40600.0
 1905 20600.0 41700.0 39800.0
 1906 18100.0 19000.0 38600.0
 1907 21400.0 13000.0 42300.0
 1908 22000.0  8300.0 44500.0
 1909 25400.0  9100.0 42100.0
 1910 27100.0  7400.0 46000.0
 1911 40300.0  8000.0 46800.0
 1912 57000.0 12300.0 43800.0
 1913 76600.0 19500.0 40900.0
 1914 52300.0 45700.0 39400.0
 1915 19500.0 51100.0 39000.0
 1916 11200.0 29700.0 36700.0
 1917  7600.0 15800.0 41800.0
 1918 14600.0  9700.0 43300.0
 1919 16200.0 10100.0 41300.0
 1920 24700.0  8600.0 47300.0


In [22]:
#ex1
#mean and std
summary = pd.DataFrame({
    'Hare': [np.mean(data[:, 1]), np.std(data[:, 1])],
    'Lynx': [np.mean(data[:, 2]), np.std(data[:, 2])],
    'Carrot': [np.mean(data[:, 3]), np.std(data[:, 3])]}, index=['Mean', 'Std'])

display(summary.round(2))

,Hare,Lynx,Carrot
Mean,34080.95,20166.67,42400.00
Std,20897.91,16254.59,3322.51


In [52]:
#ex2
#year of largest pop

hare_large = df.iloc[:, 1].argmax()
lynx_large = df.iloc[:, 2].argmax()
carrot_large = df.iloc[:, 3].argmax()

summary1 = pd.DataFrame({'Hare': [int(df.iloc[hare_large, 0])],'Lynx': [int(df.iloc[lynx_large, 0])],'Carrot': [int(df.iloc[carrot_large, 0])]},
                        index=['year of largest population'])

display(summary1)

,Hare,Lynx,Carrot
year of largest population,1903,1904,1900


In [53]:
#ex3
#

species = np.array(['H', 'L', 'C'])

order = np.argsort(data[:, 1:], axis=1)
largest = species[order[:, -1]]

summary2 = pd.DataFrame({'Year': df['Year'], 'Largest species': largest})

display(summary2)

,Year,Largest species
0,1900,C
1,1901,C
2,1902,H
3,1903,H
4,1904,L
5,1905,L
6,1906,C
7,1907,C
8,1908,C
9,1909,C


# Lecture 4.1

Agenda:
- Coding questions
- Tabs in python

Some relevant coding humor: https://www.youtube.com/watch?v=JfEIkkDkrmE

Let's go over some of the examples here: https://scipy-lectures.org/intro/language/control_flow.html

In [33]:
if 2**2 == 5:
    print('Yes!')
print('This is not in the if statement')

This is not in the if statement


In [41]:
a = 10
if a ==1:
    print('1')
elif a ==2:
    print(2)
else:
    print("it's not those")

it's not those


In [43]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [45]:
# if statement

if (x[1] == 3):
    print('yes') # there is a tab before the print statement
else:
    print('no')
    
print('Hello')    # this is not part of the if statement


no
Hello


In [46]:
x[1] == 2

np.True_

In [47]:
y = np.array([4,7,6])
y

array([4, 7, 6])

In [48]:
if (y[-1] > 7):
    print("Excellent")

print('Bogus')

Bogus


In [54]:
for i in range(4):
    print(i)

0
1
2
3


In [55]:
for i in range(3):
    print(i)
    print(y[i])

0
4
1
7
2
6


In [56]:
for i in range(3):
    print('index is ' + str(i))
    print('value is ' + str(y[i]))

index is 0
value is 4
index is 1
value is 7
index is 2
value is 6


In [57]:
x

array([1, 2, 3])

In [58]:
y

array([4, 7, 6])

In [59]:
z=[0,0,0]
for i in range(3):
    z[i] = x[i] * y[i]
    print(z[i])

4
14
18


In [61]:
type(z)

list

In [62]:
for word in ('cool', 'powerful', 'readable'):
    print('Python is %s' % word)

Python is cool
Python is powerful
Python is readable


In [65]:
for word in ('cool', 'powerful', 'readable'):
    print('Python is ' + word)

Python is cool
Python is powerful
Python is readable


In [67]:
a = [1, 0, 2, 4]
for element in a:
    if element == 0:
        continue
    print(1. / element)

1.0
0.5
0.25


comtinue skips the next code and sends you back up to the top of the for loop

# Lab 4.1

**E.1** Complete intermediate python chapter 3: Logic, Control Flow and Filtering

Note that the tutorials here have similar material for your needs:
https://github.com/chsharrison/Sci_comp_F26/blob/main/Course_materials/resources.md

**E.2** Make notes for yourself on all of the progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

In [73]:
# using comparison operators:
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

print(my_house>=18)
print(my_house<=your_house)

[ True  True False False]
[False  True  True False]


In [74]:
#and, or
my_kitchen = 18.0
your_kitchen = 14.0

print(my_kitchen > 10 and my_kitchen < 18)
print(my_kitchen < 14 or my_kitchen > 17)
print(my_kitchen * 2 < your_kitchen * 3)

False
True
True


In [75]:
#boolean with numpy
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

print(np.logical_or(my_house>18.5,my_house<10))
print(np.logical_and(my_house<11,your_house<11))

[False  True False  True]
[False False False  True]


In [77]:
#if statement
room = "kit"
area = 14.0

if room == "kit" :
    print("looking around in the kitchen.")

if area > 15:
    print("big place!")

looking around in the kitchen.


In [78]:
#if-else statement
if room == "kit" :
    print("looking around in the kitchen.")
else :
    print("looking around elsewhere.")

looking around in the kitchen.


In [79]:
#if-elif-else statement
# if-elif-else construct for room
if room == "kit" :
    print("looking around in the kitchen.")
elif room == "bed":
    print("looking around in the bedroom.")
else :
    print("looking around elsewhere.")

looking around in the kitchen.


In [89]:
#step-by-step approach to filter observations from a DataFrame based on boolean arrays: check who travelled alone in titanic
import pandas as pd

# load data
titanic = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv")
print(titanic)
# extract the alone column as a series
alone = titanic["alone"]

# keep only rows where alone is true
sel = titanic[alone]

# display the selected rows
display(sel)

# check that every selected row has alone = True
assert sel["alone"].all()

     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alo

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True


In [88]:
# same query but in one-liner
# keep rows where alone is True
sel = titanic[titanic['alone']]

# print sel
print(sel)

     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
2           1       3  female  26.0      0      0   7.9250        S   Third   
4           0       3    male  35.0      0      0   8.0500        S   Third   
5           0       3    male   NaN      0      0   8.4583        Q   Third   
6           0       1    male  54.0      0      0  51.8625        S   First   
11          1       1  female  58.0      0      0  26.5500        S   First   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
884         0       3    male  25.0      0      0   7.0500        S   Third   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alo

In [91]:
#step-by-step approach to filter observations from a DataFrame based on boolean arrays: passengers whose fare was over 100
# extract the fare column
fare = titanic['fare']

# check which fares are over 100
high_fare = fare > 100

# keep only rows where high_fare is True
expensive_tickets = titanic[high_fare]

# print the selected rows
print(expensive_tickets)

     survived  pclass     sex    age  sibsp  parch      fare embarked  class  \
27          0       1    male  19.00      3      2  263.0000        S  First   
31          1       1  female    NaN      1      0  146.5208        C  First   
88          1       1  female  23.00      3      2  263.0000        S  First   
118         0       1    male  24.00      0      1  247.5208        C  First   
195         1       1  female  58.00      0      0  146.5208        C  First   
215         1       1  female  31.00      1      0  113.2750        C  First   
258         1       1  female  35.00      0      0  512.3292        C  First   
268         1       1  female  58.00      0      1  153.4625        S  First   
269         1       1  female  35.00      0      0  135.6333        S  First   
297         0       1  female   2.00      1      2  151.5500        S  First   
299         1       1  female  50.00      0      1  247.5208        C  First   
305         1       1    male   0.92    

In [92]:
#step-by-step approach to filter observations from a DataFrame based on boolean arrays: passengers whose fare was greater than 100 and less than 500
# extract the fare column
fare = titanic['fare']

# check which fares are between 100 and 500
between = np.logical_and(fare > 100, fare < 500)

# keep rows where both conditions are True
medium = titanic[between]

# print medium
print(medium)

     survived  pclass     sex    age  sibsp  parch      fare embarked  class  \
27          0       1    male  19.00      3      2  263.0000        S  First   
31          1       1  female    NaN      1      0  146.5208        C  First   
88          1       1  female  23.00      3      2  263.0000        S  First   
118         0       1    male  24.00      0      1  247.5208        C  First   
195         1       1  female  58.00      0      0  146.5208        C  First   
215         1       1  female  31.00      1      0  113.2750        C  First   
268         1       1  female  58.00      0      1  153.4625        S  First   
269         1       1  female  35.00      0      0  135.6333        S  First   
297         0       1  female   2.00      1      2  151.5500        S  First   
299         1       1  female  50.00      0      1  247.5208        C  First   
305         1       1    male   0.92      1      2  151.5500        S  First   
306         1       1  female    NaN    

**E.3** Exercise 1 on https://www.practicepython.org

In [94]:
#user input
name = input("Give me your name: ")
print("Your name is " + name)

Give me your name:  Nahian


Your name is Nahian


In [97]:
#string manipulation 1
age = input("Enter your age: ")
age = int(age)

Enter your age:  25


In [99]:
#string manipulation 2
age = int(input("Enter your age: "))

Enter your age:  25


In [101]:
print("Were" + "wolf")
print("Door" + "man")
print("4" + "chan")
print(str(4) + "chan")
print(4 * "test")

Werewolf
Doorman
4chan
4chan
testtesttesttest


In [103]:
name = input("What is your name: ")
age = int(input("How old are you: "))
year = 2026 - age + 100
print(name + ", you will be 100 years old in the year " + str(year))

What is your name:  Nahian
How old are you:  25


Nahian, you will be 100 years old in the year 2101


**E.4** Exercise 2 on https://www.practicepython.org

In [105]:
5%3
6%3

0

In [109]:
num = input("Enter a number: ")
num = int(num)
mod = num % 2
if mod > 0:
    print("You picked an odd number.")
else:
    print("You picked an even number.")

Enter a number:  9


You picked an odd number.


Don't forget to do some practicing of what you have been learning, including material from previous labs

**You did it!**